# Generated by Django 5.1.1 on 2025-05-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='road',
            new_name='state',
        ),
    ]
